//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Misfinanzas
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Administracion_FinancieraEntities1 : DbContext
    {
        public Administracion_FinancieraEntities1()
            : base("name=Administracion_FinancieraEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cuenta> cuentas { get; set; }
        public virtual DbSet<egreso> egresoes { get; set; }
        public virtual DbSet<ingreso> ingresoes { get; set; }
        public virtual DbSet<usuario> usuarios { get; set; }
    
        public virtual ObjectResult<SP_filtroIngresos_Result> SP_filtroIngresos(Nullable<System.DateTime> fechainicio, Nullable<System.DateTime> fechafinal)
        {
            var fechainicioParameter = fechainicio.HasValue ?
                new ObjectParameter("fechainicio", fechainicio) :
                new ObjectParameter("fechainicio", typeof(System.DateTime));
    
            var fechafinalParameter = fechafinal.HasValue ?
                new ObjectParameter("fechafinal", fechafinal) :
                new ObjectParameter("fechafinal", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_filtroIngresos_Result>("SP_filtroIngresos", fechainicioParameter, fechafinalParameter);
        }
    }
}
