//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Misfinanzas
{
    using System;
    using System.Collections.Generic;
    
    public partial class cuenta
    {
        public int id_cuenta { get; set; }
        public int id_usuarios { get; set; }
        public int id_ingresos { get; set; }
        public int id_egresos { get; set; }
        public Nullable<int> monto { get; set; }
    
        public virtual egreso egreso { get; set; }
        public virtual ingreso ingreso { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
